# Site settings
title: E1110C Blog
email: guoyonghui_hit@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  E1110C的个人学习博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  E1110CNotFound
renren_userid:    474788280

# Build settings
markdown: kramdown
